### ISSUE TITLE
Arcface Onnx转换问题修改了fc1的数据类型最后显示 dimension mismatch？

### ISSUE THREAD

**Issue by Reversev** [zheshipinyinMc/arcface_retinaface_mxnet2onnx#16]
自己尝试用mobilefacenet-res2-6-10-2-dim512进行转换，得到下面的错误，求解答，代码跟作者的一样（解注释了后面几行检查和修改的语句）：
2023-05-24 17:48:29.121959761 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'fc1' source:{1,512,1,512} target:{1,512}. Falling back to lenient merge
2023-05-24 17:48:29.168708774 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Gemm node. Name:'' Status Message: GEMM: Dimension mismatch, W: {512,512} K: 1 N:512
Traceback (most recent call last):
  File "mxnet_to_onnx.py", line 155, in <module>
    onnx_inferred_demo()
  File "mxnet_to_onnx.py", line 52, in onnx_inferred_demo
    out = ort_session.run([outputs], input_feed={input_name: input_blob})
  File "/usr/local/python3/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gemm node. Name:'' Status Message: GEMM: Dimension mismatch, W: {512,512} K: 1 N:512

**Comment by Reversev** [comment]
![1684922446558](https://github.com/zheshipinyinMc/arcface_retinaface_mxnet2onnx/assets/37957969/748eeea1-ba8c-4d36-b16b-9a4fb9093b32)
看对应的网络结构，好像也没有啥问题
